name: dependency audit
on:
  push:
    branches:
      "*"

# Note, this exists: https://github.com/rustsec/audit-check
# but we chose not to use it for now since the task is very simple
# and we aren't trying to do fancy stuff like auto-fixing yet.

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup env
        uses: ./.github/actions/build_env

      - name: install cargo-audit
        run: |
          cargo install cargo-audit

      - name: run cargo-audit
        run: cargo audit
